### ISSUE TITLE
php easyswoole migrate run errors

### ISSUE THREAD

**Issue by itmeicn** [Joyboo/Joyboo-admin-easyswoole#1]
php7.4 and swoole4.8.11
#!/usr/bin/env php
PHP Fatal error:  Uncaught EasySwoole\Mysqli\Exception\Exception: SQLSTATE[HY000] [2002] Connection reset by peer or Transport endpoint is not connected in /www/wwwroot/Joyboo-admin-easyswoole/vendor/easyswoole/mysqli/src/Client.php:69
Stack trace:
#0 /www/wwwroot/Joyboo-admin-easyswoole/vendor/easyswoole/db-migrate/src/MigrateManager.php(58): EasySwoole\Mysqli\Client->execBuilder()
#1 /www/wwwroot/Joyboo-admin-easyswoole/vendor/easyswoole/db-migrate/src/MigrateCommand.php(136): EasySwoole\DatabaseMigrate\MigrateManager->query()
#2 /www/wwwroot/Joyboo-admin-easyswoole/vendor/easyswoole/db-migrate/src/MigrateCommand.php(100): EasySwoole\DatabaseMigrate\MigrateCommand->checkDefaultMigrateTable()
#3 {main}
  thrown in /www/wwwroot/Joyboo-admin-easyswoole/vendor/easyswoole/mysqli/src/Client.php on line 69

Fatal error: Uncaught EasySwoole\Mysqli\Exception\Exception: SQLSTATE[HY000] [2002] Connection reset by peer or Transport endpoint is not connected in /www/wwwroot/Joyboo-admin-easyswoole/vendor/easyswoole/mysqli/src/Client.php:69

**Comment by Joyboo** [comment]
#### 1. Please check whether the database configuration is correct, mainly in the following two files

- bootstrap.php (migrations use this configuration) 
- App/Common/Config/index.php

#### 2. Please check whether is created database : vben_ admin
